### PR TITLE
FEATURE: Allow new version of Carbon.IncludeAssets

### PR DESCRIPTION
**Pull request by jonnitto**

### CODE REVIEW

**Comment by rolandschuetz** [comment]
Since this is a specific project, why not just pin to ~5.0?

**Comment by jonnitto** [comment]
`^5.0` and `~5.0` are basically the same.

**Comment by rolandschuetz** [comment]
Yeah. Thanks for the change, I think this makes more sense. So now we are only missing the composer.lock

**Comment by jonnitto** [comment]
I've some troubles with my PHP 7.2. I can't run `composer install`, and with `composer update` it would update a whole bunch of other stuff…

**Comment by rolandschuetz** [comment]
Ok, not that easy because other packages also depend on old versions. Can't fix it now myself, it also fine with me to have the or in the package for now.
PS: We use php 7.4

**Comment by kdambekalns** [comment]
Will be part of https://github.com/neos/Neos.DocsNeosIo/pull/59

**Pull request closed without merging**
