### PR TITLE
FEATURE: Replace Google Analytics with Matomo like on neos.io

### PR DESCRIPTION
**Pull request by ahaeslich**
Changes made based on https://github.com/neos/Neos.NeosIo/pull/367

ToDo's:
- [ ] Check matomo configuration
- [ ] Check cache settings and variables
- [ ] Check after deployment todo's (see: https://github.com/neos/Neos.NeosIo/pull/367#issue-718219152)

### CODE REVIEW

**Comment by markusguenther** [comment]
Used your commit also in https://github.com/neos/Neos.DocsNeosIo/pull/100

**Comment by ahaeslich** [comment]
@Sebobo and/or @regniets I did add docs.neos.io in our matomo instance. It would be good if you could check the config there.

**Comment by Sebobo** [comment]
What do you mean with `caching`?

**Comment by ahaeslich** [comment]
I mean the config in Caches.yaml. They differ in comparison to Neos.in and use just slightly different env-variables in dev an production which irritated me. It's just a small issue in my opinion.

**Comment by ahaeslich** [comment]
Closing it because it is already integrated with the merge of https://github.com/neos/Neos.DocsNeosIo/pull/100

**Pull request closed without merging**
