### PR TITLE
TASK: Markup improvements

### PR DESCRIPTION
**Pull request by jonnitto**
- [x] Strim css class in tag list
- [x] Remove unnecessary span in `Neos.DocsNeosIo:Component.Authors`
- [x] Minify Neos Logo
- [x] Refactor Footer
- [x] Extract Text from render section
- [x] Improve generation of hash

### CODE REVIEW

**Comment by rolandschuetz** [comment]
@jonnitto 

 - Why are you replacing `'` with `"` in AFX? There seems to be no standard and no rule of what to you.
 - Refactor Footer: I don't see the value of this, we have almost 50% more code, more complexity and it's harder to understand. What is on the positive side to gain here?
 - Extract Text from render section. Ok, but why?

**Comment by jonnitto** [comment]
@rolandschuetz 
1. Make it consistent with the rest of the fusion code
2. You don't have to search for the data, it is above the renderer section like that
3. It's more DRY like this. And also easier to change / translate

**Comment by rolandschuetz** [comment]
1. It's not. I wrote all AFX code in this project in double quotes and most of the AFX documentation also uses double quotes.
2. A very small plus, because if the content changes the layout will most likely also change.
3. Guess that's a matter of taste. We do not plan to make it multilingual in the near future, and if so many other places would need to be translated as well.

**Comment by jonnitto** [comment]
I have reverted some changes 😉

**Pull request merged**
